language: scala
scala:
- 2.11.4
sudo: false
before_install:
- "./scripts/installMongo mongodb-linux-x86_64-2.6.9 mongo2.6 27018"
- "./scripts/installMongo mongodb-linux-x86_64-3.0.4 mongo3.0 27019"
script: "./scripts/build"
after_success: "./scripts/buildSuccess"
after_failure: "./scripts/buildFailure"
notifications:
  irc:
    template:
    - "%{result}: %{repository_slug}#%{build_number} (%{branch}@%{commit}: %{author})
      %{build_url}"
  slack:
    secure: KPCXtCAjtlpRQcH7TQtprrf67yIqPVpht9L6/+wbbNd14Tj3x53fiZ3OTabHVx3SL2ZWxbWq+FJGxdIFMyxC/fC0bV9flB7PlRtqHJV1Q7g49odAMAZL7syWr7vFP5bJt+TXuxHvMBihDHFk1Cehy4a1cnrOMReDgqGIFCwQtbI=
env:
  global:
  - LOCAL_MONGODB=true
  - ISOLATED_ENV=true
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/