language: scala
scala: 2.11.8 # but this setting isn't used when there's an explicit script
jdk: oraclejdk8
sudo: false
script:
  - export MONGO_LINUX="MONGO_${MONGO_RELEASE}_LINUX"
  - export MONGO_PORT="MONGO_${MONGO_RELEASE}_PORT"
  - export MONGO_AUTH="MONGO_${MONGO_RELEASE}_AUTH"
  - ./scripts/installMongo mongodb-linux-x86_64-${!MONGO_LINUX} mongo ${!MONGO_PORT} ${!MONGO_AUTH}
  - ./scripts/build $MONGO_RELEASE
after_success: ./scripts/afterSuccess
notifications:
  irc:
    template:
    - "%{result}: %{repository_slug}#%{build_number} (%{branch}@%{commit}: %{author})
      %{build_url}"
  slack:
    secure: KPCXtCAjtlpRQcH7TQtprrf67yIqPVpht9L6/+wbbNd14Tj3x53fiZ3OTabHVx3SL2ZWxbWq+FJGxdIFMyxC/fC0bV9flB7PlRtqHJV1Q7g49odAMAZL7syWr7vFP5bJt+TXuxHvMBihDHFk1Cehy4a1cnrOMReDgqGIFCwQtbI=

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt

before_cache:
- find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
- find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm

env:
  matrix:
  - MONGO_RELEASE=2_6
  - MONGO_RELEASE=3_0
  - MONGO_RELEASE=3_0_RO
  - MONGO_RELEASE=3_2
  global:
  - LOCAL_MONGODB=true
  - ISOLATED_ENV=true
  - MONGO_2_6_LINUX=2.6.11
  - MONGO_2_6_PORT=27018
  - MONGO_2_6_AUTH=""
  - MONGO_3_0_LINUX=3.0.7
  - MONGO_3_0_PORT=27019
  - MONGO_3_0_AUTH=""
  - MONGO_3_0_RO_LINUX=3.0.9
  - MONGO_3_0_RO_PORT=27019
  - MONGO_3_0_RO_AUTH="--auth"
  - MONGO_3_2_LINUX=3.2.3
  - MONGO_3_2_PORT=27020
  - MONGO_3_2_AUTH=""
