language: scala
scala:
  - 2.11.2
services:
  - mongodb
script:         "./scripts/build"
after_success:  "./scripts/buildSuccess"
after_failure:  "./scripts/buildFailure"
notifications:
  irc:
    channels:
      - "chat.freenode.net#slamdata"
    template:
      - "%{result}: %{repository_slug}#%{build_number} (%{branch}@%{commit}: %{author}) %{build_url}"
env:
  - TRAVIS_BUILD=true
  - "SLAMDATA_MONGODB={\"mongodb\":{\"database\": \"test\", \"connectionUri\": \"mongodb://localhost:127.0.0.1\"}}"