sudo: false
language: scala
scala: 2.11.8 # but this setting isn't used when there's an explicit script
jdk: oraclejdk8
script: ./bin/run-travis.sh

addons:
  apt:
    packages:
      - moreutils # for ts

notifications:
  irc:
    template:
    - "%{result}: %{repository_slug}#%{build_number} (%{branch}@%{commit}: %{author})
      %{build_url}"
  slack:
    secure: KPCXtCAjtlpRQcH7TQtprrf67yIqPVpht9L6/+wbbNd14Tj3x53fiZ3OTabHVx3SL2ZWxbWq+FJGxdIFMyxC/fC0bV9flB7PlRtqHJV1Q7g49odAMAZL7syWr7vFP5bJt+TXuxHvMBihDHFk1Cehy4a1cnrOMReDgqGIFCwQtbI=

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt

before_cache:
- find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
- find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm

# At the momenet only the first two jobs are run on pull requests,
# so those get mongo 3.2 as the most relevant and fastest.
env:
  matrix:
  - MONGO_RELEASE=3_2 CODE_COVERAGE=true
  - MONGO_RELEASE=3_2
  - MONGO_RELEASE=2_6
  - MONGO_RELEASE=3_0
  - MONGO_RELEASE=3_0_RO
