#!/usr/bin/env bash
#

source "./bin/bashlib.sh"

# Create a tag/release on github, and upload the already-built JAR.
# Using curl to POST to the github API.
if [[ ! -v GITHUB_TOKEN ]] ; then
    echo "GITHUB_TOKEN not defined, skipping publishing JAR"

    exit 0
fi

# only publish on quasar-analytics/quasar#master
if [[ "$TRAVIS" == "true" && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_REPO_SLUG" == "quasar-analytics/quasar" ]] ; then
  "$SBT" 'project repl' githubRelease 'project web' githubRelease
else
  echo "GITHUB_TOKEN defined, but Travis not running in quasar-analytics/quasar#master, so skipping publish"
fi
