#!/usr/bin/env bash

if ! type "aws" > /dev/null; then
  pip install awscli --user
fi

TARGETS=".targets"
HOARDER=".hoarder-cache"
TRAVISIP=$(curl -s checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//')

echo "Trivs public IP is: $TRAVISIP"
./scripts/credentials

if [[ "$1" = "upload" ]]; then
  aws s3 --only-show-errors cp $TARGETS s3://quasar-build-cache/$TRAVIS_BUILD_NUMBER/$TARGETS --recursive
  aws s3 --only-show-errors cp $HOARDER s3://quasar-build-cache/$TRAVIS_BUILD_NUMBER/$HOARDER --recursive
elif [[ "$1" = "download" ]]; then
  aws s3 --only-show-errors cp s3://quasar-build-cache/$TRAVIS_BUILD_NUMBER/$TARGETS $TARGETS --recursive
  aws s3 --only-show-errors cp s3://quasar-build-cache/$TRAVIS_BUILD_NUMBER/$HOARDER $HOARDER --recursive
elif [[ "$1" = "cleanup" ]]; then
  aws s3 --only-show-errors rm s3://quasar-build-cache/$TRAVIS_BUILD_NUMBER --recursive)
else
  echo "Usage: ./scripts/s3Cache upload | download | cleanup"
fi
