#!/usr/bin/env bash

set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

dir=$(dirname $0)

deployCredentials() {
  pwd
  source scripts/credentials
}

installAwsCli() {
  if [[ $(command -v aws) = "1" ]]; then
    pip install --user awscli
  fi
}

checkTravisIP() {
  curl -s checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//'
}

cpFromS3() {
  travis_retry aws s3 --only-show-errors cp s3://quasar-build-cache/$TRAVIS_BUILD_NUMBER/$1 $1 --recursive
}

cpToS3() {
  travis_retry aws s3 --only-show-errors cp $1 s3://quasar-build-cache/$TRAVIS_BUILD_NUMBER/$1 --recursive
}

rmFromS3() {
  travis_retry aws s3 --only-show-errors rm s3://quasar-build-cache/$TRAVIS_BUILD_NUMBER --recursive
}

if [[ $# -eq 0 ]]; then
  echo "Usage: ./scripts/s3Cache upload | download | cleanup"
  exit 1
fi

deployCredentials
installAwsCli
echo "Trivs public IP is: $(checkTravisIP)"

if [[ $1 = "upload" ]]; then
  cpToS3 .targets
  cpToS3 .hoarder-cache
  exit 0
elif [[ $1 = "download" ]]; then
  cpFromS3 .targets
  cpFromS3 .hoarder-cache
  exit 0
elif [[ $1 = "cleanup" ]]; then
  rmFromS3
  exit 0
fi
