#!/usr/bin/env bash
#

source "./bin/bashlib.sh"
set -v

# NB: This assumes Linux
CONFIG_DIR=$HOME/.config/quasar
CONFIG_FILE=$CONFIG_DIR/quasar-config.json

if [ ! -e $CONFIG_FILE ]
then
    mkdir -p $CONFIG_DIR
    cp $(dirname $0)/../example-quasar-config.json $CONFIG_FILE
fi

QUASAR_SUCCESS_OUTPUT="Server started listening on port"
QUASAR_LOG_FILE="$TEMP_DIR/quasarout.log"

echo "Launching Quasar JAR..."

java -verbose -jar "$QUASAR_WEB_JAR_PATH" |& tee "$QUASAR_LOG_FILE" &
QUASAR_PID=$!

echo "Quasar PID: $QUASAR_PID"

sleep 10s
cat "$QUASAR_LOG_FILE"

echo "Killing Quasar JAR..."
kill -9 $QUASAR_PID
KILL_STATUS=$?
echo "Status code from killing Quasar: $KILL_STATUS"

if grep -q "$QUASAR_SUCCESS_OUTPUT" "$QUASAR_LOG_FILE"; then
  echo "Quasar successfully started"
else
  echo "Quasar failed to start"
  cat "$QUASAR_LOG_FILE"
  exit 1
fi
